### ISSUE TITLE
PropTypes is being imported from React package

### ISSUE THREAD

**Issue by tuccle22** [nisargrthakkar/react-redux-starter-kit#1]
This isn't a bug, but looks like a simple mistake.  In the PostPageView.js file you are importing PropTypes from React, but React v16 doesn't include PropTypes and PropTypes aren't used in this file anyway.

**Comment by nisargrthakkar** [comment]
Thank you @tuccle22  yes this is a mistake from my side. After React v16 PropType is not part of React (https://reactjs.org/docs/typechecking-with-proptypes.html) and also I am not using PropType in a file.

So I removed PropType from the code and closing this issue.
